modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/enhanced-farming/issues"
license="MIT"

[[mods]]
modId="enhancedfarming"
version="${file.jarVersion}"
displayName="Enhanced Farming"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhanced-farming"
authors="Mrbysco"
description='''
A rewritten version of the Better Farming mod
'''
credits="iBlackShadow for the original idea"
[[dependencies.enhancedfarming]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.enhancedfarming]]
modId="neoforge"
type="required"
versionRange="[21.0.96-beta,)"
ordering="NONE"
side="BOTH"